### ISSUE TITLE
Drawing the path issues

### ISSUE THREAD

**Issue by sylviafrank8** [agary110/CS112-Final-Project#1]
In order to draw the paths, I think that we need to be in the same class that draws the original JPanel (because we need to use the same graphics object). So, I figured out the code to draw each instance of a path (straight, corner, etc) but I'm not sure if it'll work to draw it in a file that's not Game.java?

**Comment by apass831** [comment]
Do you think it would work if we moved all of the Draw Methods in the World class to the Game class? As far as I'm aware, I don't think they rely on any variables that are specific to the World class.

**Comment by sylviafrank8** [comment]
Right now the draw methods are implemented in the World class but I defined them in each other path subclasses (because they're different for different types of path) so maybe we should somehow move those to the Game class? Also it might work in the Path subclasses I'm just not sure bc we would have to run all the files at once and i feel like there would be so many other errors that we wouldn't be able to tell.

**Comment by sylviafrank8** [comment]
I'll look into it and see what I find

**Comment by apass831** [comment]
Okay, let's talk more during class or at lunch once you get out of class

**Comment by sylviafrank8** [comment]
I added the methods to the World class and I think it'll work a lot better-- also that part of the code compiles (there are some other errors in separate code that we need to debug).
